### ISSUE TITLE
Content-Length = 0 for request that doesnt contain it

### ISSUE THREAD

**Issue by declspec-cdecl** [dream11/zio-http#100]
`Request.Data.headers` contains header `Content-Length = 0` for request that doesnt contain it

**Comment by declspec-cdecl** [comment]
it seems that the presence of header is netty [internal feature](https://github.com/netty/netty/blob/e5951d46fc89db507ba7d2968d2ede26378f0b04/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectAggregator.java#L230) . Still can't understand why it's so needed. Isn't the purpose of FullHttpMessage to represent corresponding http request maximum accurately. If so, why should we add header that doesn't exist in original query? So in our turn we can try to remove content-length=0 for GET requests from headers collection or consider the question as inessential. Any thoughts are welcome.

**Comment by tusharmath** [comment]
It might be getting added because of `HttpObjectAggregator` need some digging around.

**Comment by declspec-cdecl** [comment]
So the issue must be closed?

**Comment by tusharmath** [comment]
Thanks!
