### ISSUE TITLE
Router DSL: impossible to describe a route that serves nested assets

### ISSUE THREAD

**Issue by guizmaii** [dream11/zio-http#1281]
I'm using the 1.0.0-RC7 version of zio-http.

As discussed in Discord with @amitksingh1490, there's an issue in the router DSL: **it seems impossible to describe a route that serves nested assets.**

I have the following resources directories structure:
```
resources/
- static/
-- index.html
-- assets/
--- style.css
--- spa.js
--- img/
---- a.png
```

I want to write a route that will serve all the files in the `resources/static/assets` directory if the user is making an HTTP request like this: `GET <host>/assets/<path to file>`.
Some concrete HTTP requests examples:
 - `GET <host>/assets/style.css`
 - `GET <host>/assets/spa.js`
 - `GET <host>/assets/img/a.png`
 

**Solution 1**
The correct way to write this route with zio-http seems to be to write (if we forget about potential security concerns):
 
```scala
Http.collectHttp[Request] {
  case Method.GET -> !! / "assets" /: path => fromResource(s"static/assets/$path")
}
```

but this doesn't compile.
The compiler will complain with the following error:
```scala
[error] MyClass.scala: left- and right-associative operators with same precedence may not be mixed
[error]       case Method.GET -> !! / "assets" /: path   => fromResource(s"static/assets/$path")
```

**Solution 2**
Another way to write this route would be to write:
```scala
Http.collectHttp[Request] {
  case Method.GET -> !! / "assets" / path => fromResource(s"static/assets/$path")
}
```
(notice the that we're not using the `/:` operator anymore here)

This solution compiles and serve correctly these requests:
 - `GET <host>/assets/style.css`
 - `GET <host>/assets/spa.js`

but doesn't work for nested assets and so will not serve this request:

 - `GET <host>/assets/img/a.png`
 
 **Solution 3**
 Another way to write this route, suggested by @amitksingh1490 in Discord, would be to write:
 ```scala
Http.collectHttp[Request] {
  case Method.GET -> "assets" /: path => fromResource(s"static/assets/$path")
}
```
(notice that I remove the initial `!! /` and only use the `/:` operator now)

This solution is problematic because it does serve all my requests in my unit tests but when I package and run my app, then none of the assets is served.
It answers 404s:

<img width="798" alt="Screen Shot 2022-06-01 at 10 11 06 am" src="https://user-images.githubusercontent.com/1193670/171361902-36f3c25d-ed3f-492b-8d63-8e5bde8e532d.png">

<img width="703" alt="Screen Shot 2022-06-01 at 10 11 10 am" src="https://user-images.githubusercontent.com/1193670/171361941-61cc5118-3d0d-4972-960a-53f2b53433d3.png">

**Comment by tusharmath** [comment]
**Solution 1** Should work by making this change —

```scala

Http.collectHttp[Request] {
  case Method.GET -> "assets" /: path => fromResource(s"static/assets/$path")
}
```

**IGNORE:** I just read how the first solution was implemented :)

**Comment by tusharmath** [comment]
@guizmaii  Shouldn't this get fixed via #1267 ? 

If not, then for the time being I would recommend using `Http.fromPath` and supply the exact path if possible (via a config or env variable)?

**Comment by guizmaii** [comment]
@tusharmath Ok I've found why the **solution 3** doesn't work and how to fix it. 

The `path` variable type in this solution is `Path`. When we call `.toString` on it, it gives this: `/<path to file>`.
For example:
- `/script.js`
- `/style.css`
- `/img/a.png`

while I was expecting:
- `script.js`
- `style.css`
- `img/a.png`

So to fix this solution I need to write:
```scala
case Method.GET -> "assets" /: path if isAuthorizedAsset(path.toString()) => fromResource(s"static/assets$path")
```

**Comment by guizmaii** [comment]
@tusharmath 

> Shouldn't this get fixed via https://github.com/dream11/zio-http/pull/1267 ?

No, it doesn't sadly. 
The `fromResource` function I'm using in my example is the code from my PR
See:
```scala
private def fromResource(path: String): HttpApp[Any, Throwable] = {
    @inline def header[A](v: A)(f: A => Headers): Headers = if (v == null) Headers.empty else f(v)

    Http
      .getResource(path)
      .flatMap { url =>
        val response =
          effectBlocking {
            val connection = url.openConnection()
            val mediaType  =
              path.lastIndexOf(".") match {
                case -1 => None
                case i  => MediaType.forFileExtension(path.substring(i + 1)).map(_.fullType)
              }

            val contentLengthHeader   = header(connection.getContentLengthLong)(Headers.contentLength)
            val contentTypeHeader     = header(mediaType.orNull)(Headers.contentType)
            val contentEncodingHeader = header(connection.getContentEncoding)(Headers.contentEncoding)
            val data                  = ZStream.fromInputStream(connection.getInputStream).provideLayer(Blocking.live)

            Response(
              headers = contentLengthHeader ++ contentTypeHeader ++ contentEncodingHeader,
              data = HttpData.fromStream(data),
            )
          }

        Http.fromZIO(response)
      }
      .provideLayer(Blocking.live)
  }
```

**Comment by guizmaii** [comment]
IMO, that'd be nice if we can find a solution to make **solution 1** compile. To me, it's the most consistent and less surprising solution

**Comment by tusharmath** [comment]
Actually solution 1 is just not possible because of the compiler. Solution 3 is the right way to use this DSL.

**Comment by guizmaii** [comment]
Would it maybe be possible to have a `:/` operator (or something similar) that we could use this way:

```scala
Http.collectHttp[Request] {
  case Method.GET -> !! / "assets" :/ path => fromResource(s"static/assets/$path")
}
```
?

With a request such as `GET <host>/assets/img/a.png` would put the `String` `"img/a.png"` in the `path` variable? WDYT?

**Comment by gciuloaica** [comment]
@guizmaii 
There is no need for a new combinator. With the latest changes in `Path` DSL you can achieve what you want with a small change in the route as below:

```scala
case Method.GET -> "" /: "assets" /: path  => fromResource(s"static/assets$path")
```

**Comment by gciuloaica** [comment]
Closing this issue as being resolved.
