### ISSUE TITLE
Let the server to be terminated programmatically

### ISSUE THREAD

**Issue by gipeshka** [dream11/zio-http#146]
Hey guys!

I've been playing around with the project and was going to try to build some integration tests, basically starting http server for a spec and terminating it afterwards. Though I found myself unable to shut it down programmatically.

I suppose that to be a useful feature for a server.

Best regards.

**Comment by tusharmath** [comment]
Hi @gipeshka great that you are trying out ZIO Http, we are looking forward to knowing your feedback!

Did you checkout the advanced example here — https://github.com/dream11/zio-http/blob/main/example/src/main/scala/HelloWorldAdvanced.scala#L37

```scala
server.make
      .use(_ =>
        // Write your ZIO based integration tests.
        // Once the tests are completed, the server will exit automatically.
        runIntegrationTests,
      )
      .provideCustomLayer(ServerChannelFactory.auto ++ EventLoopGroup.auto(nThreads))
      .exitCode
```

**Comment by tusharmath** [comment]
Hope this solves your issue. Feel free to reopen the issue if the suggested solution doesn't work.

**Comment by gipeshka** [comment]
hey @tusharmath, thanks! It helped, I was using RC13 and it didn't have `use` as I can see. After I've updated to RC15 it works like a charm.
