### ISSUE TITLE
ZIO Http benchmark source code link appears incorrect

### ISSUE THREAD

**Issue by jxtps** [dream11/zio-http#168]
On the benchmark doc page ( https://github.com/dream11/zio-http/blob/main/BENCHMARKS.md ), there’s a link to the source code ( https://github.com/dream11/zio-http/blob/main/example/src/main/scala/HelloWorldAdvanced.scala ). 

However, the example code doesn’t appear to have /text and /json endpoints defined?!

What source was actually used for the benchmark? Thanks!

**Comment by tusharmath** [comment]
Thanks for reporting @jxtps 
I think over time the example kept on getting updated as the API changed. We will add the actual benchmark code in a separate file/project.
