### ISSUE TITLE
Addition of authentication middleware for Routes.

### ISSUE THREAD

**Issue by aposto** [dream11/zio-http#173]
For example.
 case Method.GET -> Root / "health" => Response.ok

to

 case Method.GET -> AuthRoot / "health" => ...

**Comment by tusharmath** [comment]
@aposto You can checkout this example added here — https://github.com/dream11/zio-http/pull/175/files#diff-0b5120d305a9d6ec4ea512ff2b965bfe94ea7c69a0a6e93162c7ceb6ecca87ee

**Comment by aposto** [comment]
@tusharmath Thank you so much for this support.
I think we can introduce it to our lightweight micro-services.

**Comment by tusharmath** [comment]
Fixed in #175
