### ISSUE TITLE
Publish to Maven

### ISSUE THREAD

**Issue by Devian-ua** [dream11/zio-http#19]
Hi, will you make a release to maven repo?

**Comment by amitksingh1490** [comment]
Yes working on it.

**Comment by jamesward** [comment]
Thanks for this! BTW, I noticed the release is not cross-published for multiple Scala versions. Details: https://www.scala-sbt.org/1.x/docs/Cross-Build.html

**Comment by amitksingh1490** [comment]
> Thanks for this! BTW, I noticed the release is not cross-published for multiple Scala versions. Details: https://www.scala-sbt.org/1.x/docs/Cross-Build.html

Opened an issue #31  for this will pick it up.
