### ISSUE TITLE
Adding a managed behavior to Apps

### ISSUE THREAD

**Issue by remiguittaut** [dream11/zio-http#218]
It would be interesting to add a managed behavior to websocket connections, guaranteeing an uninterrutible release operation to be executed on connection close (success, error, timeout).

Another interest would be to be able to close a connection by releasing the managed.

This behavior can even be extended to regular Http apps.

A proposed API just for the release guarantee "app-wide" would be something like:
```scala
private val socketApp =
    SocketApp.open(open) ++                                // Called after the request is successfully upgraded to websocket
      SocketApp.message(echo merge fooBar) ++              // Called after each message being received on the channel
      SocketApp.close(_ => console.putStrLn("Closed!")) ++ // Called after the connection is closed
      SocketApp.error(_ => console.putStrLn("Error!")) ++  // Called whenever there is an error on the socket channel
      SocketApp.decoder(decoder) ++
      SocketApp.protocol(protocol) ++
      SocketApp.release( => UIO[Unit] )
```

On websocket protocol upgrade, in an `HttpApp`, we could have something like:
```scala
val app =
    HttpApp.collectManaged {
      case Method.GET -> Root / "greet" / name  => ZManaged.succeed(Response.text(s"Greetings ${name}!"))
      case Method.GET -> Root / "subscriptions" => socketApp.toManaged( f: SocketApp => UIO[Unit] )
    }
````
This supposes that `HttpApp` is extended to collect `ZManaged[R, E, ResponseM[R, E]]`.
(The release could eventually also contain an environment requirement, to access the SocketApp environment?).

Another interest is that with this addition, we could, by keeping a reference to the created `ZManaged` and be able to interrupt an http response (useful?) or a SocketApp (i.e. closing the socket) by releasing the managed.

Additionally, as the `Server` has a managed behavior (`server.make` returns a managed if I'm not mistaken), it should be very easy to compose in the internal implementation..

**Comment by tusharmath** [comment]
Added #866 to support `collectManaged`. Resources will be release automatically and uninterruptedly when the connection closes.

**Comment by tusharmath** [comment]
Feel free to open the issue again incase your use case isn't supported this way.
