### ISSUE TITLE
Scalafix error when running HelloWorld example

### ISSUE THREAD

**Issue by willemvermeer** [dream11/zio-http#22]
Hi,
When trying to run the example HelloWorld from an otherwise empty project, sbt will initially crash with error:
ThisBuild / scalafixScalaBinaryVersion from Global / scalafixInterfaceProvider ((scalafix.sbt.ScalafixPlugin.globalSettings) ScalafixPlugin.scala:213)

this can be resolved by creating a project/plugins.sbt with the following line:
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.26")

It would be great if this could be added to the documentation or maybe this implicit dependency can somehow be removed.

Thanks!
Willem

**Comment by tusharmath** [comment]
This should be fixed now @willemvermeer. You can add ZIO Http as a dependency.

**Comment by willemvermeer** [comment]
Confirmed, thanks!
