### ISSUE TITLE
Unable to use zio-http as simple http client [Support request]

### ISSUE THREAD

**Issue by jlcanela** [dream11/zio-http#229]
I’m trying to use zio-http as simple http client library with the SimpleClient example.

When I run the following code : 
```scala
object SimpleClient extends App {
  val env = ChannelFactory.auto ++ EventLoopGroup.auto()

  val program = for {
    _ <- console.putStrLn("Start")
    res <- Client.request("https://api.github.com/users/zio/repos")
    _ <- console.putStrLn("Finish")
    _ <- console.putStrLn {
      res.content match {
        case HttpData.CompleteData(data) => data.map(_.toChar).mkString
        case HttpData.StreamData(_)      => "<Chunked>"
        case HttpData.Empty              => ""
      }
    }
  } yield ()

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = program.exitCode.provideCustomLayer(env)

}
```

Current Behavior:  When I run the sample code the request is not executed and the program is frozen
```
sbt:hello> run
[info] running SimpleClient 
Start
```

Expected Behavior:  When I run the sample code *res.content* is displayed

Sample code : https://github.com/jlcanela/zhttp-client

Any help welcome, I’m 99% sure I did something stupid but cannot find it at the moment.

**Comment by ShrutiVerma97** [comment]
@jlcanela Client has a bug and I am working on it. Thanks for reporting.
