### ISSUE TITLE
Release for 3.0.0?

### ISSUE THREAD

**Issue by psylinse** [dream11/zio-http#252]
I noticed you're building against 3.0.0. Any chance you can do a release for 3.0.0 vs. the RC3?

Thanks!

**Comment by tusharmath** [comment]
We will be making an RC release soon. In the meantime you can try the snapshot release.

**Comment by amitksingh1490** [comment]
**ZIO-Http** 1.0.0.0-RC-17 is released with **Scala 3.0.0** support
https://repo1.maven.org/maven2/io/d11/zhttp_3/1.0.0.0-RC17/

**Comment by psylinse** [comment]
Thank you!
