### ISSUE TITLE
Adding zio-http repo to Scala-Steward, for keeping dependencies updated 

### ISSUE THREAD

**Issue by shankarshastri** [dream11/zio-http#30]
For more information:
Using Scala-Steward, for keeping dependencies updated.
https://github.com/scala-steward-org/scala-steward

**Comment by sh0hei** [comment]
Added repos `dream11/zio-http` to scala-steward.
cf. https://github.com/scala-steward-org/repos/pull/620

**Comment by tusharmath** [comment]
Thank you @sh0hei
