### ISSUE TITLE
Scala 3 CI Integration

### ISSUE THREAD

**Issue by tusharmath** [dream11/zio-http#59]
Make sure the library is compatible with Scala 3.

**Comment by brbrown25** [comment]
I'd be willing to assist with this if you're interested.

**Comment by tusharmath** [comment]
@brbrown25 That will be awesome!

**Comment by brbrown25** [comment]
Awesome! I'll have some free cycles this week and I'll work up a pr.

**Comment by tusharmath** [comment]
fixed #62

**Comment by loicdescotte** [comment]
Hi, is it possible to publissh a ZIO-HTTP version for Scala 3.0 RC3?
Thanks :)
