### ISSUE TITLE
Server Sent Events support

### ISSUE THREAD

**Issue by loicdescotte** [dream11/zio-http#77]
Server Sent Events are simpler to use than Websocket for unidirectional push on HTTP.
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

It would be nice to be able to push a ZStream where each chunk is a data line in the SSE format, for example 

 `data: {"time": "1616750897"}`
 `data: {"time": "1616750952"}`
`...`.

**Comment by tusharmath** [comment]
This should now be possible after after #143
